### PR TITLE
fix(README): manage updating already installed docker

### PR DESCRIPTION
**Pull request by zrangerz**

### CODE REVIEW

**Comment by abuecker** [comment]
Commit message style bro:

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

```
fix(README): manage updating already installed docker
```

**Comment by abuecker** [comment]
```
$ git commit --amend
# put in correct message
$ git push origin readme-update-docker-if-installed --force
```

**Comment by zrangerz** [comment]
SUPER weird. Hub just didn't run properly as that's exactly what it showed me in VIM: fix(README): manage updating already installed docker. 

Fixing

**Comment by zrangerz** [comment]
I'll figure out hub on the next PR. I think I messed it up with not pushing to my remote branch first.

**Comment by abuecker** [comment]
:+1:

**Pull request merged**
